name: translator
description: "translator for android smartwatches"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "000000"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
